# See https://jekyllrb.com/docs/configuration/options/

# Site/SEO settings
email: umayrh@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

# the directory where Jekyll will write files
destination:
  docs

name: Umayr Hassan
title: Sketchy Polytopes
description: >
  Algorithms, optimization; systems, data, and people 
url: http://umayrh.github.io
default_img: /assets/images/form_contact.jpg
social:
  - name: linkedin
    url: https://www.linkedin.com/in/umayr/
  - name: github
    url: https://github.com/umayrh
  - name: gitlab
    url: https://gitlab.com/umayrh
  - name: wordpress
    url: https://umayrh.wordpress.com

# Contact settings
contact_img: /assets/images/form_contact.jpg
formcarry: https://formcarry.com/s/UuffFC2ATgC

# Disqus settings
disqus: 

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Umayr Hassan
    url: http://umayrh.github.io

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Sketchy Polytopes'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
excerpt_separator: "\n\n"
markdown: kramdown
kramdown:
  auto_ids: true
highlighter: rouge
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
